### ISSUE TITLE
firmware for the gh80-3003

### ISSUE THREAD

**Issue by specs32** [evyd13/gh80-series#2]
I cannot seem to find a matching firmware for this board on qmk.fm.
only gh80_1800 and gh80_3700 are there, can you point me in the right direction ?

**Comment by evyd13** [comment]
It's the generic gh80_3000 keymap, they're designed to use the same one 😉

**Comment by specs32** [comment]
omg... sittin on my eyes.. thanks for all the incredible stuff btw !
